// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu-cKWkdS1Sgrnh6fxvwrWd9j66UjHY4g',
    appId: '1:413921141762:web:b3823a48eae0251fe8331b',
    messagingSenderId: '413921141762',
    projectId: 'mybh-bank',
    authDomain: 'mybh-bank.firebaseapp.com',
    storageBucket: 'mybh-bank.firebasestorage.app',
    measurementId: 'G-KY2MB781BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnaVUUEpbDafyoAFwKXb1Qd1hOs9mINY4',
    appId: '1:413921141762:android:1a74346097edd655e8331b',
    messagingSenderId: '413921141762',
    projectId: 'mybh-bank',
    storageBucket: 'mybh-bank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9KuRIgLq1pbkJRj10xLovZwcEpWFvFOg',
    appId: '1:413921141762:ios:76700d2995b10923e8331b',
    messagingSenderId: '413921141762',
    projectId: 'mybh-bank',
    storageBucket: 'mybh-bank.firebasestorage.app',
    androidClientId: '413921141762-ol1qe3nqmc6vr3dj10k062d9ot4u8hbr.apps.googleusercontent.com',
    iosClientId: '413921141762-c66ageqpejthpt85mh20366j1bdjnf5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9KuRIgLq1pbkJRj10xLovZwcEpWFvFOg',
    appId: '1:413921141762:ios:76700d2995b10923e8331b',
    messagingSenderId: '413921141762',
    projectId: 'mybh-bank',
    storageBucket: 'mybh-bank.firebasestorage.app',
    androidClientId: '413921141762-ol1qe3nqmc6vr3dj10k062d9ot4u8hbr.apps.googleusercontent.com',
    iosClientId: '413921141762-c66ageqpejthpt85mh20366j1bdjnf5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu-cKWkdS1Sgrnh6fxvwrWd9j66UjHY4g',
    appId: '1:413921141762:web:57f9cd7722c0a484e8331b',
    messagingSenderId: '413921141762',
    projectId: 'mybh-bank',
    authDomain: 'mybh-bank.firebaseapp.com',
    storageBucket: 'mybh-bank.firebasestorage.app',
    measurementId: 'G-FZBXC7M4JC',
  );
}